apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-34vw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-34vw
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-34vw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-34vw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-34vw
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nhib-tenant/rhtap-demo-app/hacbs-test-project-34vw@sha256:3c9b611658757663a26cf4d6746ccf00de161daa7b745b705d22319fbd082fc1
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
